export const peopleRu = [
  {
    name: "Иван",
    surname: "Иванов",
    age: 25,
    city: "Москва",
    country: "Россия",
    gender: "мужской",
    imageUrl: "./images/ru/ivan-ivanov/photo1.jpg",
    id: 1,
  },
  {
    name: "Анна",
    surname: "Смирнова",
    age: 32,
    city: "Санкт-Петербург",
    country: "Россия",
    gender: "женский",
    imageUrl: "./images/ru/anna-smirnova/photo1.jpg",
    id: 2,
  },
  {
    name: "Александр",
    surname: "Зуев",
    age: 27,
    city: "Тольятти",
    country: "Россия",
    gender: "мужской",
    imageUrl: "./images/ru/alexandr-zuev/photo1.jpg",
    id: 3,
  },
  {
    name: "Татьяна",
    surname: "Минина",
    age: 17,
    city: "Анапа",
    country: "Россия",
    gender: "женский",
    imageUrl: "./images/ru/tatyana-minina/photo1.jpg",
    id: 4,
  },
  {
    name: "Милана",
    surname: "Воронцова",
    age: 23,
    city: "Сочи",
    country: "Россия",
    gender: "женский",
    imageUrl: "./images/ru/milana-vorontsova/photo1.jpg",
    id: 5,
  },
  {
    name: "Ксения",
    surname: "Адамова",
    age: 24,
    city: "Екатеринбург",
    country: "Россия",
    gender: "женский",
    imageUrl: "./images/ru/ksenya-adamova/photo1.jpg",
    id: 6,
  },
  {
    name: "Виталий",
    surname: "Альтов",
    age: 28,
    city: "Екатеринбург",
    country: "Россия",
    gender: "мужской",
    imageUrl: "./images/ru/vitaly-altov/photo1.jpg",
    id: 7,
  },
  {
    name: "Глеб",
    surname: "Барон",
    age: 36,
    city: "Уфа",
    country: "Россия",
    gender: "мужский",
    imageUrl: "./images/ru/gleb-baron/photo1.jpg",
    id: 8,
  },
  {
    name: "Иван",
    surname: "Даль",
    age: 41,
    city: "Москва",
    country: "Россия",
    gender: "мужской",
    imageUrl: "./images/ru/ivan-dal/photo1.jpg",
    id: 9,
  },
  {
    name: "Кира",
    surname: "Кавецкая",
    age: 36,
    city: "Санкт-Петербург",
    country: "Россия",
    gender: "женский",
    imageUrl: "./images/ru/kira-kavetskaya/photo1.jpg",
    id: 10,
  },
];

export const peopleEu = [
  {
    name: "John",
    surname: "Doe",
    age: 40,
    city: "New York",
    country: "USA",
    gender: "male",
    imageUrl: "./images/eu/john-doe/photo1.jpg",
  },
  {
    name: "Jane",
    surname: "Smith",
    age: 28,
    city: "Los Angeles",
    country: "USA",
    gender: "female",
    imageUrl: "./images/eu/jane-smith/photo1.jpg",
  },
  {
    name: "Alice",
    surname: "Allen",
    age: 45,
    city: "Washington",
    country: "USA",
    gender: "female",
    imageUrl: "./images/eu/alice-allen/photo1.jpg",
  },
  {
    name: "Nathan",
    surname: "Amio",
    age: 32,
    city: "Atlanta",
    country: "USA",
    gender: "male",
    imageUrl: "./images/eu/nathan-amio/photo1.jpg",
  },
  {
    name: "Mark",
    surname: "Gross",
    age: 20,
    city: "Houston",
    country: "USA",
    gender: "male",
    imageUrl: "./images/eu/mark-gross/photo1.jpg",
  },
  {
    name: "Sean",
    surname: "Dice",
    age: 26,
    city: "Chicago",
    country: "USA",
    gender: "male",
    imageUrl: "./images/eu/sean-dice/photo1.jpg",
  },
  {
    name: "Robert",
    surname: "Carter",
    age: 33,
    city: "Houston",
    country: "USA",
    gender: "male",
    imageUrl: "./images/eu/robert-carter/photo1.jpg",
  },
  {
    name: "Michael",
    surname: "Corso",
    age: 51,
    city: "San Jose",
    country: "USA",
    gender: "male",
    imageUrl: "./images/eu/michael-corso/photo1.jpg",
  },
  {
    name: "Martin",
    surname: "Milli",
    age: 37,
    city: "Dallas",
    country: "USA",
    gender: "male",
    imageUrl: "./images/eu/martin-milli/photo1.jpg",
  },
  {
    name: "Carl",
    surname: "Parker",
    age: 23,
    city: "Los Angeles",
    country: "USA",
    gender: "male",
    imageUrl: "./images/eu/carl-parker/photo1.jpg",
  },
];
